config/routes.rb
Rails.application.routes.draw do

  resources :contracts

  resources :devices do 
		member do 
			put "detach_sim"
		end
	end

	root "home#index"
  get 'home/index'

  devise_for :users, controllers: {sessions: "users/sessions"}
  resources :sims do 
	end

	resources "users" do 
		collection do 
			get "current"
		end
	end

end

app/models/contract.rb
class Contract < ActiveRecord::Base
	belongs_to :user

	def from_sim
		return Sim.find(self.from_sim_id) rescue nil
	end

	def to_sim
		return Sim.find(self.to_sim_id) rescue nil
	end


	def kind
		from_sim_id, to_sim_id = self.from_sim_id, self.to_sim_id

		if from_sim_id && to_sim_id
			return :mnp
		elsif from_sim_id && !to_sim_id
			return :cancel
		elsif !from_sim_id && to_sim_id
			return :new
		else
			# must not be here
		end
	end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate_user!

  # GET /contracts
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1
  def show
  end

  # GET /contracts/new
  def new
		sims = Sim.where(user_id: current_user.id).select(&:available?)
		@from_sim_options = sims.dup.map{|sim| [sim.number, sim.id]} << ["not selected", ""]
		@to_sim_options = sims.dup.map{|sim| [sim.number, sim.id]} << ["not selected", ""]

    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  def create
    @contract = Contract.new(contract_params)
		@contract.user = current_user

		from_sim_id, to_sim_id = @contract.from_sim_id, @contract.to_sim_id

		if from_sim_id == to_sim_id
			logger.debug "#{from_sim_id}, #{to_sim_id}"
			redirect_to( {action: :new}, alert: "from_sim and to_sim must not same") and return
		end

		# in MNP or cancel, SIM card can be made unavailable
		if @contract.save
			if params[:disable_sim] and Sim.exists?(from_sim_id)
				Sim.find(from_sim_id).update(available: false)
			end
			redirect_to @contract, notice: 'Contract was successfully created.'
		else
			render :new
		end
  end

  # PATCH/PUT /contracts/1
  def update
		if @contract.update(contract_params)
			redirect_to @contract, notice: 'Contract was successfully updated.'
		else
			render :edit
		end
  end

  # DELETE /contracts/1
  def destroy
    @contract.destroy
    redirect_to contracts_url, notice: 'Contract was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      contract = Contract.find(params[:id])
			unless contract.user == current_user
				redirect_to contracts_url, alert: "Not your resource" and return
			end
			@contract = contract
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contract_params
      params.require(:contract).permit(:from_sim_id, :to_sim_id, :processed_at, :description)
    end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.haml
= form_for @contract do |f|
  - if @contract.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contract.errors.count, "error")} prohibited this contract from being saved:"
      %ul
        - @contract.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :from_sim_id
    = select_tag("contract[from_sim_id]",  options_for_select(@from_sim_options, selected: ""))
  .field
    = label_tag "Make SIM card disabled"
    = check_box_tag "disable_sim"
  .field
    = f.label :to_sim_id
    = select_tag("contract[to_sim_id]",  options_for_select(@to_sim_options, selected: ""))
  .field
    = f.label :processed_at
    = f.date_select :processed_at
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/contracts/edit.html.haml
%h1 Editing contract

= render 'form'

= link_to 'Show', @contract
\|
= link_to 'Back', contracts_path

app/views/contracts/index.html.haml
%h1 Listing contracts

%table.table.table-condensed
  %tr
    %th From sim
    %th To sim
    %th Processed at
    %th Description
    %th User
    %th Kind
    %th
    %th
    %th

  - @contracts.each do |contract|
    %tr
      %td= contract.from_sim_id
      %td= contract.to_sim_id
      %td= contract.processed_at
      %td= contract.description
      %td= contract.user_id
      %td= contract.kind
      %td= link_to 'Show', contract
      %td= link_to 'Edit', edit_contract_path(contract)
      %td= link_to 'Destroy', contract, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Contract', new_contract_path

app/views/contracts/new.html.haml
%h1 New contract

= render 'form'

= link_to 'Back', contracts_path

app/views/contracts/show.html.haml
%p#notice= notice

%p
  %b From sim:
  = @contract.from_sim_id
%p
  %b To sim:
  = @contract.to_sim_id
%p
  %b Processed at:
  = @contract.processed_at
%p
  %b Description:
  = @contract.description
%p
  %b User:
  = @contract.user_id
%p
  %b Kind:
  = @contract.kind

= link_to 'Edit', edit_contract_path(@contract)
\|
= link_to 'Back', contracts_path