config/routes.rb
Rails.application.routes.draw do

  resources :contracts

  resources :devices do 
		member do 
			put "detach_sim"
		end
	end

	root "home#index"
  get 'home/index'

  devise_for :users, controllers: {sessions: "users/sessions"}
  resources :sims do 
	end

	resources "users" do 
		collection do 
			get "current"
		end
	end

end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :user
	belongs_to :sim
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy, :detach_sim]
	before_filter :authenticate_user!
	before_filter :set_sims_options, only: [:new, :edit]

  # GET /devices
  def index
		@devices = Device.where(user_id: current_user.id)
  end

  # GET /devices/1
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
		sims = Sim.where(user_id: current_user.id)
  end

  # POST /devices
	def create
		@device = Device.new(device_params)
		@device.user_id = current_user.id

		if @device.save
			redirect_to @device, notice: 'Device was successfully created.'
		else
			render :new
		end
	end

	# PATCH/PUT /devices/1
	def update
		if @device.update(device_params)
			redirect_to @device, notice: 'Device was successfully updated.' 
		else
			render :edit 
		end
	end

  # DELETE /devices/1
  def destroy
		@device.destroy
		redirect_to devices_url, notice: 'Device was successfully destroyed.'
  end

	# PUT /devices/1
	def detach_sim
		@device.update(sim: nil)
		
		# back to previous location
		redirect_to Rails.application.routes.recognize_path(request.referer)
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      device = Device.find(params[:id])
			unless device.user_id == current_user.id
				redirect_to devices_url, alert: "Not your device" and return
			end

			@device = device

    end

		def set_sims_options
			sims = Sim.where(user_id: current_user.id) + [nil]
			options = sims.map do |sim|
				if sim.nil?
					["(detached)", nil]
				elsif sim == @device.sim
					["#{sim.number} (attached)"]
				else
					[sim.number, sim.id]
				end
			end

			@sims_options = options
		end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:sim_id, :model_number, :name, :imei, :description)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.haml
= form_for @device do |f|
  - if @device.errors.any?
    #error_explanation
      %h2= "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      %ul
        - @device.errors.full_messages.each do |msg|
          %li= msg

  .field
    = label_tag "SIM"
    = select_tag("device[sim_id]",  options_for_select(@sims_options, selected: @device.sim ? @device.sim.id : ""))
    = link_to("Detach", detach_sim_device_path, method: :put)
  .field
    = f.label :model_number
    = f.text_field :model_number
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :imei
    = f.text_field :imei
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%h1 Your Devices

%table.table.table-condensed
  %tr
    %th Sim
    %th Model number
    %th Name
    %th Imei
    %th Description
    %th
    %th
    %th

  - @devices.each do |device|
    %tr
      %td 
        - if sim = device.sim
          = link_to(image_tag("sim_icon.png", height: 20), sim_path(sim))
      %td= device.model_number
      %td= device.name
      %td= device.imei
      %td= device.description
      %td= link_to 'Show', device
      %td= link_to 'Edit', edit_device_path(device)
      %td= link_to 'Destroy', device, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Device', new_device_path

app/views/devices/new.html.haml
%h1 New device

= render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.haml
%p#notice= notice

%p
  %b Sim:
  = @device.sim_id
%p
  %b User:
  = @device.user_id
%p
  %b Model number:
  = @device.model_number
%p
  %b Name:
  = @device.name
%p
  %b Imei:
  = @device.imei
%p
  %b Description:
  = @device.description

= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path