config/routes.rb
Rails.application.routes.draw do

  resources :contracts

  resources :devices do 
		member do 
			put "detach_sim"
		end
	end

	root "home#index"
  get 'home/index'

  devise_for :users, controllers: {sessions: "users/sessions"}
  resources :sims do 
	end

	resources "users" do 
		collection do 
			get "current"
		end
	end

end

app/models/sim.rb
class Sim < ActiveRecord::Base
	belongs_to :user
	has_one :device

	def find_by_user(user)
		
	end

	def attached_device
		if Device.exists?(sim: self)
			return Device.find_by(sim: self)
		end

		return nil
	end
end

app/controllers/sims_controller.rb
class SimsController < ApplicationController
	before_action :set_sim, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate_user!

	# GET /sims
	def index
		@sims = Sim.where(user_id: current_user.id)
	end

	# GET /sims/1
	def show
	end

	# GET /sims/new
	def new
		@sim = Sim.new
	end

	# GET /sims/1/edit
	def edit
	end

	# POST /sims
	def create
		@sim = Sim.new(sim_params)
		@sim.user_id = current_user.id

		if @sim.save
			redirect_to @sim, notice: 'Sim was successfully created.'
		else
			render :new 
		end
	end

	# PATCH/PUT /sims/1
	def update
		if @sim.update(sim_params)
			redirect_to @sim, notice: 'Sim was successfully updated.'
		else
			render :edit
		end
	end

	# DELETE /sims/1
	def destroy
		@sim.destroy
		redirect_to sims_url, notice: 'Sim was successfully destroyed.'
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_sim
		sim = Sim.find(params[:id])
		unless sim.user_id == current_user.id
			redirect_to sims_url, alert: "Selected SIM card is not yours" and return
		end

		@sim = sim
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def sim_params
		params.require(:sim).permit(:carrior, :number, :available, :registered_at, :imsi)
	end
end

app/helpers/sims_helper.rb
module SimsHelper
end

app/views/sims/_form.html.haml
= form_for @sim do |f|
  - if @sim.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sim.errors.count, "error")} prohibited this sim from being saved:"
      %ul
        - @sim.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :carrior
    = f.text_field :carrior
  .field
    = f.label :number
    = f.text_field :number
  .field
    = f.label :available
    = f.check_box :available
  .field
    = f.label :registered_at
    = f.date_select :registered_at
  .field
    = f.label :imsi
    = f.text_field :imsi
  .actions
    = f.submit 'Save'

app/views/sims/edit.html.haml
%h1 Editing sim

= render 'form'

= link_to 'Show', @sim
\|
= link_to 'Back', sims_path

app/views/sims/index.html.haml
%h1 Your SIM cards

%table.table.table-condensed
  %tr
    %th 
    %th Carrior
    %th Number
    %th Valid
    %th Registered at
    %th Imsi
    %th User
    %th
    %th
    %th

  - @sims.each do |sim|
    %tr
      %td
        - if device = sim.attached_device
          = link_to(image_tag("phone_icon.png", height: 20), device_path(device))
      %td= sim.carrior
      %td= sim.number
      %td= sim.available
      %td= sim.registered_at
      %td= sim.imsi
      %td= sim.user_id
      %td= link_to 'Show', sim
      %td= link_to 'Edit', edit_sim_path(sim)
      %td= link_to 'Destroy', sim, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sim', new_sim_path

app/views/sims/new.html.haml
%h1 New sim

= render 'form'

= link_to 'Back', sims_path

app/views/sims/show.html.haml
%p#notice= notice

%p
  %b Carrior:
  = @sim.carrior
%p
  %b Number:
  = @sim.number
%p
  %b Available:
  = @sim.available
%p
  %b Registered at:
  = @sim.registered_at
%p
  %b Imsi:
  = @sim.imsi
%p
  %b User:
  = @sim.user_id

= link_to 'Edit', edit_sim_path(@sim)
\|
= link_to 'Back', sims_path